name: version_manipulation
version: 0.0.1
description: Extension on Dart `pub_semver` library. Provides `nextBuild` and `change`.
homepage: https://github.com/f3ath/dart-version-manipulation
dependencies:
  pub_semver: ^1.4.4
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0
environment:
  sdk: ">=2.8.0 <3.0.0"

