name: version_manipulation
version: 0.0.5
homepage: https://github.com/f3ath/dart-version-manipulation
description: Extension on Dart `pub_semver` library. Provides `nextBuild` and `change`.
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  pub_semver: ^1.4.4
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0
  test_coverage: ^0.4.3

